name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Website repo
        uses: actions/checkout@v4

      - name: Checkout Key-Definitions repo
        uses: actions/checkout@v4
        with:
          repository: precision-agronomy-research-center/Key-Definitions
          path: key-definitions

      - name: Prepare site content
        run: |
          mkdir -p site-content
          cp -r * site-content/
          cp -r key-definitions/* site-content/key-definitions/

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site-content

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4